### ISSUE TITLE
tumblr で HTTPS を有効にするとブロックされるコンテンツがある

### ISSUE THREAD

**Issue by hiyosi** [sanographix/tumblr#16]
tumblr の設定で "常にブログをSSLで処理する" を設定した場合、いくつかのコンテンツがブロックされるようです。

こちらで確認できたものは以下です。
- "http://b.st-hatena.com/js/bookmark_button.js"
- "http://fonts.googleapis.com/css?family=Open+Sans:400,700"
- "http://b.st-hatena.com/js/bookmark_button.js"
- "http://b.st-hatena.com/images/entry-button/button-only@2x.png"

以下の環境で確認しております。

- OS: macOS Sierra (10.12.3)
- ブラウザ: Firefox 51.0.1 (64 ビット)

**Comment by hiyosi** [comment]
HTML を編集し、それぞれ https に変更するとブロックされないことも確認しております。

**Comment by hiyosi** [comment]
現在設定しているテーマについて記載できておりませんでした。
上記の事象はテーマ Apollo にて確認したものです。

**Comment by sanographix** [comment]
@hiyosi ご報告ありがとうございます。対応しました。 https://github.com/sanographix/tumblr/pull/17
